---
- name: 'Add the vagrant user to the docker group'
  hosts: 'all'
  gather_facts: true
  become: true

  tasks:

    - name: 'Add vagrant user to docker group'
      ansible.builtin.user:
        name: 'vagrant'
        groups:
          - 'docker'
        append: true
